# Generated by Django 3.2.19 on 2023-05-30 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('parol', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Xabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xabar', models.TextField()),
                ('user_fk', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiy.user')),
            ],
        ),
    ]
