# Generated by Django 3.2.19 on 2023-05-30 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asosiy', '0003_user_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Talaba',
        ),
        migrations.AlterField(
            model_name='xabar',
            name='user_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
